name = "Axiom"
uuid = "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
authors = ["Axiom.jl Contributors"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
SMTLib = "7d3f9a2c-8b4e-5c1f-a6d0-9e8f7b2c3d4e"

[weakdeps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[extensions]
AxiomCUDAExt = "CUDA"
AxiomPyTorchExt = "PyCall"

[compat]
julia = "1.9"
SMTLib = "0.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
